#!/usr/bin/env node
// Configure this workspace for an agent harness, or start a session.
//
//   node scripts/learn.mjs setup dsh|claude|codex|all
//   node scripts/learn.mjs dsh [extra dsh web args…]   # setup + start DeepSeek Harness Web UI
//
// Each harness gets the same two things:
//   • the skills in .agents/skills (teach, visualize)
//   • the `learn` MCP server (mcp/src/server.mjs) for graded quizzes
// Generated files contain absolute paths, so they are gitignored and rebuilt
// on every setup.

import { spawnSync } from "node:child_process";
import { cpSync, existsSync, lstatSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SERVER = join(ROOT, "mcp", "src", "server.mjs");
const DSH_PATCH = join(ROOT, "harness", "dsh", "learn.cordis.yml");
const isWindows = process.platform === "win32";

// On Windows, npm/npx/codex are .cmd shims that need a shell, and the shell
// splits unquoted arguments on spaces (e.g. "C:\Program Files\nodejs\node.exe").
const shellQuote = (a) => (isWindows && /\s/.test(a) ? `"${a}"` : a);

function run(cmd, args, opts = {}) {
	const res = spawnSync(cmd, args.map(shellQuote), { stdio: "inherit", shell: isWindows, ...opts });
	if (res.error) throw res.error;
	return res.status ?? 1;
}

function onPath(cmd) {
	const res = spawnSync(isWindows ? "where" : "which", [cmd], { stdio: "ignore" });
	return res.status === 0;
}

function ensureServerDeps() {
	if (existsSync(join(ROOT, "mcp", "node_modules", "@modelcontextprotocol", "sdk"))) return;
	console.log("Installing learn MCP server dependencies…");
	if (run("npm", ["install", "--no-fund", "--no-audit"], { cwd: join(ROOT, "mcp") }) !== 0) {
		throw new Error("npm install failed in mcp/");
	}
}

// YAML accepts JSON strings, which handles spaces and Windows backslashes.
const q = (s) => JSON.stringify(s);

function setupDsh() {
	mkdirSync(dirname(DSH_PATCH), { recursive: true });
	writeFileSync(
		DSH_PATCH,
		`# Generated by scripts/learn.mjs — do not edit; re-run setup instead.
# Connects the learn MCP server to DeepSeek Harness. Its tools appear as
# mcp__learn__quiz_create / quiz_grade / quiz_summary. Skills load from
# <project>/.agents/skills automatically and AGENTS.md is read as instructions.
- insert:
    - id: learn-mcp
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: learn
        transport: stdio
        command: ${q(process.execPath)}
        args: [${q(SERVER)}]
        cwd: ${q(ROOT)}
`,
	);
	console.log(`✓ DeepSeek Harness patch written: ${DSH_PATCH}`);
	console.log(`  Start with:  node scripts/learn.mjs dsh`);
	console.log(`  (or, from this directory:  npx @deepseek-ai/dsh web --patch ${q(DSH_PATCH)})`);
}

function setupClaude() {
	writeFileSync(
		join(ROOT, ".mcp.json"),
		JSON.stringify({ mcpServers: { learn: { command: process.execPath, args: [SERVER] } } }, null, 2) + "\n",
	);
	console.log("✓ Claude Code: .mcp.json written (approve the 'learn' server when Claude Code asks)");

	// .claude/skills is a committed symlink to ../.agents/skills. Checkouts
	// without symlink support turn it into a plain file; replace it with a copy.
	// A copy made by an earlier run is refreshed so skill edits carry over.
	const link = join(ROOT, ".claude", "skills");
	const workingLink = lstatSafe(link)?.isSymbolicLink() && existsSync(join(link, "teach", "SKILL.md"));
	if (!workingLink) {
		rmSync(link, { recursive: true, force: true });
		mkdirSync(dirname(link), { recursive: true });
		cpSync(join(ROOT, ".agents", "skills"), link, { recursive: true });
		console.log("  .claude/skills was not a working symlink; copied .agents/skills instead (re-run setup after editing skills)");
	}
	console.log("  Start with:  claude   (from this directory)");
}

function lstatSafe(p) {
	try {
		return lstatSync(p);
	} catch {
		return undefined;
	}
}

function setupCodex() {
	const args = ["mcp", "add", "learn", "--", process.execPath, SERVER];
	if (onPath("codex")) {
		spawnSync("codex", ["mcp", "remove", "learn"], { stdio: "ignore", shell: isWindows });
		if (run("codex", args) !== 0) throw new Error("codex mcp add failed");
		console.log("✓ Codex: registered the 'learn' MCP server");
	} else {
		console.log("• Codex CLI not found on PATH. After installing it, run:");
		console.log(`    codex ${args.map((a) => (/\s/.test(a) ? q(a) : a)).join(" ")}`);
	}
	console.log("  Codex reads AGENTS.md and .agents/skills from this directory. Start with:  codex");
}

function startDsh(extra) {
	ensureServerDeps();
	setupDsh();
	const args = ["-y", "@deepseek-ai/dsh@latest", "web", "--patch", DSH_PATCH, ...extra];
	console.log(`\nStarting DeepSeek Harness: npx ${args.join(" ")}\n`);
	process.exit(run("npx", args, { cwd: ROOT }));
}

const [cmd, target, ...rest] = process.argv.slice(2);
const SETUPS = { dsh: setupDsh, claude: setupClaude, codex: setupCodex };

try {
	if (cmd === "setup" && (SETUPS[target] || target === "all")) {
		ensureServerDeps();
		for (const [name, fn] of Object.entries(SETUPS)) if (target === "all" || target === name) fn();
	} else if (cmd === "dsh") {
		startDsh([target, ...rest].filter((a) => a !== undefined));
	} else {
		console.log(`Usage:
  node scripts/learn.mjs setup dsh|claude|codex|all
  node scripts/learn.mjs dsh [extra dsh web args]`);
		process.exit(cmd ? 1 : 0);
	}
} catch (err) {
	console.error(`Error: ${err.message}`);
	process.exit(1);
}
